In [10]:
#Section A- Exception Handling

In [11]:
#1
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except TypeError:
        print("Error: Invalid data type.")

    finally:
        print("Operation attempted.")


# Test cases
safe_divide(10, 2)
safe_divide(10, 0)
safe_divide("10", 2)

Result: 5.0
Operation attempted.
Error: Cannot divide by zero.
Operation attempted.
Error: Invalid data type.
Operation attempted.


In [12]:
#2
class InvalidAgeError(Exception):
    pass


def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Age must be between 0 and 120.")
    print("Valid Age:", age)


ages = [25, -5, 150]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Invalid Age Error:", e)

Valid Age: 25
Invalid Age Error: Age must be between 0 and 120.
Invalid Age Error: Age must be between 0 and 120.


In [13]:
#3
user_inputs = ['10', 'abc', '0', '5']

for value in user_inputs:
    try:
        num = int(value)
        result = 100 / num
        print("Result:", result)

    except ValueError:
        print("ValueError: Input is not a number.")

    except ZeroDivisionError:
        print("ZeroDivisionError: Cannot divide by zero.")

    except Exception as e:
        print("Other Error:", e)

Result: 10.0
ValueError: Input is not a number.
ZeroDivisionError: Cannot divide by zero.
Result: 20.0


In [16]:
# Section B- Numpy

In [14]:
#4
import numpy as np

arr = np.arange(1, 21)

# a
arr_2d = arr.reshape(4, 5)
print(arr_2d)

# b
print("Row Sum:", arr_2d.sum(axis=1))
print("Column Sum:", arr_2d.sum(axis=0))

# c
print("Greater than 10:", arr[arr > 10])

# d
arr[arr % 2 == 0] = -1
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row Sum: [15 40 65 90]
Column Sum: [34 38 42 46 50]
Greater than 10: [11 12 13 14 15 16 17 18 19 20]
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [15]:
#5
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# a
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A * B)

# b
print("Matrix Multiplication:\n", np.dot(A, B))

# c
print("Transpose of A:\n", A.T)

# d
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
#6
import numpy as np

np.random.seed(42)

arr = np.random.randint(1, 101, 15)

print("Array:", arr)

# a
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

# b
print("Descending:", np.sort(arr)[::-1])

# c
indices = np.argsort(arr)[-3:]
print("Indices of 3 largest values:", indices)

# d
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized Array:", normalized)

Array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean: 58.06666666666667
Median: 72.0
Std Dev: 31.4843170836247
Min: 3
Max: 100
Descending: [100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]
Indices of 3 largest values: [10  1 11]
Normalized Array: [0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [18]:
#Section C- Pandas Basics

In [19]:
#7
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a
print(df.head(3))
print(df.dtypes)

# b
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 75:
        return "B"
    else:
        return "C"

df["Grade"] = df["Score"].apply(grade)

# c
print(df.sort_values(by="Score", ascending=False))

# d
print(df[df["Department"] == "AI"])

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [20]:
#8
# a
print(df.groupby("Department")["Score"].mean())

# b
print(df.loc[df["Score"].idxmax()])

# c
df.rename(columns={"Score": "Marks"}, inplace=True)
print(df)

# d
df2 = df.drop("Age", axis=1)
print(df2)

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64
Name            Meera
Age                22
Department    Web Dev
Score              95
Grade               A
Name: 3, dtype: object
    Name  Age    Department  Marks Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C
    Name    Department  Marks Grade
0  Aarav            AI     88     B
1  Priya  Data Science     92     A
2  Karan            AI     79     B
3  Meera       Web Dev     95     A
4  Sahil  Data Science     67     C


In [21]:
#9
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a
print(df.isnull().sum())

# b
mean_price = df["Price"].mean()
df["Price"].fillna(mean_price, inplace=True)

# c
df = df.dropna(subset=["Stock"])

# d
df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


/tmp/ipykernel_6246/699339652.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(mean_price, inplace=True)


In [22]:
#10
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")

    # a
    print("Shape:", df.shape)
    print("Columns:", df.columns)

    # b
    df["Total_Value"] = df["Price"] * df["Stock"]
    print(df)

    # c
    print(df.describe())

except FileNotFoundError:
    print("Error: File does not exist.")

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='object')
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
