In [1]:
# Numpy

In [2]:
%pip install numpy

In [3]:
import numpy as np

In [6]:
#Creating Arrays

In [7]:
sample_array = np.array([1,2,3,4])

In [8]:
sample_array

array([1, 2, 3, 4])

In [10]:
# 2D Array(matrix)

In [13]:
sample_array2 = np.array([[1,2],[3,4]])

In [14]:
sample_array2


array([[1, 2],
       [3, 4]])

In [15]:
array_2 = np.array([[54,64],[67,74]])

In [16]:
array_2

array([[54, 64],
       [67, 74]])

In [41]:
# 3D Array

In [31]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [42]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
#Dimension
#0-D Array(Scalar) 5
#1-D Array(Vector) [1,2,3,4]
#2-D Array(matrix) (rows,columns)
#3-D Array(tensor) (page,row,columns)

In [34]:
#Array properties

In [35]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [36]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
#shape
sample_array.shape

(2, 3)

In [38]:
#dimensions
sample_array.ndim

2

In [39]:
#total elements
sample_array.size

6

In [43]:
#data type
sample_array.dtype

dtype('int64')

In [44]:
sample_tensor = np.array([[[53,62],[34,74]],[[65,67],[87,98]]])

In [45]:
sample_tensor.shape

(2, 2, 2)

In [46]:
sample_tensor.ndim

3

In [47]:
sample_tensor.size

8

In [48]:
sample_tensor.dtype

dtype('int64')

In [49]:
# Special Arrays

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [58]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [59]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [61]:
#Indexing & Slicing

In [62]:
sample_array = np.array([10,20,30,40])

In [63]:
sample_array

array([10, 20, 30, 40])

In [64]:
sample_array[0]

np.int64(10)

In [65]:
sample_array[2]

np.int64(30)

In [66]:
sample_array[-1]

np.int64(40)

In [67]:
#Array operation

In [68]:
b = np.array([4,5,6])

In [69]:
a = np.array([1,2,3])

In [70]:
a

array([1, 2, 3])

In [71]:
b

array([4, 5, 6])

In [72]:
a+b

array([5, 7, 9])

In [73]:
a-b

array([-3, -3, -3])

In [74]:
a*b

array([ 4, 10, 18])

In [75]:
a/b

array([0.25, 0.4 , 0.5 ])

In [76]:
a//b

array([0, 0, 0])

In [77]:
# Mathematical Functions

In [78]:
sample_array = np.array([1,4,9])

In [79]:
sample_array

array([1, 4, 9])

In [80]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [81]:
array_2 = np.array([16,169,144,25])

In [82]:
np.sqrt(array_2)

array([ 4., 13., 12.,  5.])

In [83]:
np.exp(array_2)

array([8.88611052e+06, 2.48752493e+73, 3.45466066e+62, 7.20048993e+10])

In [84]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [85]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [87]:
np.log(array_2)

array([2.77258872, 5.12989871, 4.9698133 , 3.21887582])

In [88]:
# statistical Functions

In [89]:
sample_array = np.array([1,2,3,4,5])

In [90]:
sample_array

array([1, 2, 3, 4, 5])

In [91]:
np.mean(sample_array)

np.float64(3.0)

In [92]:
np.median(sample_array)

np.float64(3.0)

In [93]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [94]:
np.min(sample_array)

np.int64(1)

In [95]:
np.max(sample_array)

np.int64(5)

In [96]:
# Reshaping Arrays

In [99]:
sample_array = np.arange(6)

In [100]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [104]:
reshaped = sample_array.reshape(2,3)

In [105]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
# Flattening

In [107]:
sample_array = np.array([[1,2],[3,4]])

In [108]:
sample_array.flatten()

array([1, 2, 3, 4])

In [110]:
array_3 = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])

In [111]:
array_3

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [112]:
array_3.flatten()

array([1, 2, 3, 4, 6, 7, 8, 9])

In [113]:
# Joining array

In [114]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,6,7,8])

In [117]:
array_1

array([1, 2, 3, 4])

In [118]:
array_2

array([5, 6, 7, 8])

In [121]:
np.concat((array_1,array_2))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
sample = np.array([7,85,9,3])

In [123]:
sample

array([ 7, 85,  9,  3])

In [125]:
np.array_split(sample,2)

[array([ 7, 85]), array([9, 3])]

In [126]:
# Random Module

In [127]:
np.random.rand(3)

array([0.22457924, 0.89468754, 0.68393278])

In [128]:
np.random.randint(1,10,5)

array([5, 1, 5, 9, 8])

In [129]:
# Axis Concept

In [130]:
a2 = np.array([[12,78],[89,45]])

In [131]:
a2

array([[12, 78],
       [89, 45]])

In [132]:
np.sum(a2,axis=0)

array([101, 123])

In [140]:
np.sum(a2,axis=1)

array([ 90, 134])

In [134]:
# NaN & Missing values

In [136]:
sample_array = np.array([1,np.nan,3])

In [137]:
sample_array

array([ 1., nan,  3.])

In [139]:
np.isnan(sample_array)

array([False,  True, False])

In [141]:
#create two np array and perform element wise addition, substraction multiplication and modules operations

In [155]:
arr = np.array([1,2,3,4])

In [156]:
arr

array([1, 2, 3, 4])

In [157]:
arr2 = np.array([5,6,7,8])

In [158]:
arr2


array([5, 6, 7, 8])

In [160]:
arr+arr2

array([ 6,  8, 10, 12])

In [161]:
arr-arr2

array([-4, -4, -4, -4])

In [162]:
arr*arr2

array([ 5, 12, 21, 32])

In [163]:
arr/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [164]:
arr%arr2

array([1, 2, 3, 4])

In [165]:
arr//arr2

array([0, 0, 0, 0])